### PR TITLE
Trying to add NicknamesMatcher

### PR DESCRIPTION
**Pull request by benoittgt**
Don't understand why it returns number... :/

```
     Assertion with == failed
     code: PhubMe.NicknamesMatcher.match_nicknames(tuples_with_matching_nicknames) == {:ok, comment_with_nicknames, [['@Hannah', '@HannahSlack'], ['@lucie', '@lulu']], "baxterthehacker", "https://github.com/comment"}
     lhs:  {:ok, "Hey @HannahArrendt you should take a look at @lucie", [[64, 72, 97, 110, 110, 97, 104, 83, 108, 97, 99, 107], ""], "baxterthehacker", "https://github.com/comment"}
     rhs:  {:ok, "Hey @HannahArrendt you should take a look at @lucie", [['@Hannah', '@HannahSlack'], ['@lucie', '@lulu']], "baxterthehacker", "https://github.com/comment"}
     stacktrace:
       test/lib/phubme/nicknames_matcher_test.exs:18: (test)
```

### CODE REVIEW

**Comment by benoittgt** [comment]
BTW I think this code is complicated, and it probably doesn't need to be so complicated.

**Comment by DavidVII** [comment]
I'm on mobile, but I have a feeling that you're using single quote (apostrophe) for strings instead of quotes.

**Comment by DavidVII** [comment]
Single vs double quotes in elixir actually make a difference. I'm on mobile, otherwise I'd post some links or some code examples here :(

**Comment by nicoolas25** [comment]
Hello, something is also strange in this PR: 

``` elixir
  defp matching_nicknames([github_nick_head | github_nick_tail], matched_nicknames, array_position) do
    matched_nicknames = List.insert_at(matched_nicknames, array_position, nickname_from_mix_config(github_nick_head))
    matching_nicknames(github_nick_tail, matched_nicknames, array_position + 1)
  end
```

Maybe you're thinking like if `=` is an assignation operator but it is a matching operator. Once `matched_nicknames` is bound to a value it won't change. See http://elixir-lang.org/getting-started/pattern-matching.html#the-match-operator

Strangely your error seems to be unrelated with that, yet. The link @DavidVII talked about the CharList / String difference may be http://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html and it seems to be very related to one of the difference in the expectation. As you see there is also a structural difference.

**Comment by benoittgt** [comment]
@DavidVII You were right. I was using simple quote in the config file. That was causing the issue. 

@nicoolas25 Thanks Nicolas for your feedbacks and links. I've change few things on the last commit. I just need to do a proper management when matching nickname are not found.

**Comment by benoittgt** [comment]
Ok. Now I'm good but the way I'm creating array with matching nicknames doesn't seem functional at all.

Also I get a warning 

```
warning: the variable "matched_nicknames" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end
```

I've tried to set a function that return 

``` elixir
if nickname_from_mix_config(github_nick_head) == :error do
  IO.puts "No matching nickname found for " <> List.first(github_nick_head)
else
  matched_nicknames = List.insert_at(matched_nicknames, array_position, (github_nick_head ++ nickname_from_mix_config(github_nick_head)))
end
```

But when their is no matching nickname it returns a `nil`...

I've the same issue if I try to do. 

``` elixir
defp matching_nicknames([github_nick_head | github_nick_tail], matched_nicknames, array_position) do
    matched_nicknames =
      if nickname_from_mix_config(github_nick_head) == :error do
        IO.puts "No matching nickname found for " <> List.first(github_nick_head)
      else
        List.insert_at(matched_nicknames, array_position, (github_nick_head ++ nickname_from_mix_config(github_nick_head)))
      end
    matching_nicknames(github_nick_tail, matched_nicknames, array_position + 1)
  end
```

Still not confident at all about what I'm writing.

**Comment by nicoolas25** [comment]
I'm just looking at the last piece of code in the previous comment...

The `matching_nicknames` function expect a list as second argument. If `matched_nicknames` is set by the first branch of the `if` statement then it would be `nil` and not a list. Did you tried something like the following code?

``` elixir
defp matching_nicknames([github_nick_head | github_nick_tail], matched_nicknames, array_position) do
    updated_matched_nicknames =
      if nickname_from_mix_config(github_nick_head) == :error do
        IO.puts "No matching nickname found for " <> List.first(github_nick_head)
        matched_nicknames
      else
        List.insert_at(matched_nicknames, array_position, (github_nick_head ++ nickname_from_mix_config(github_nick_head)))
      end
    matching_nicknames(github_nick_tail, updated_matched_nicknames, array_position + 1)
  end
```

After it works, you could try to use the more idiomatic way:

``` elixir
defp matching_nicknames([ head | tail ])
  case nickname_from_mix_config(head) do
    :error -> matching_nicknames(tail)
    { :ok, nickname } -> [ head | nickname | matching_nicknames(tail) ]
  end
end

defp matching_nicknames([])
  []
end
```

If you need the tail-call-optimization, you can at least iterate from a simpler solution. What do you think of this?

**Comment by benoittgt** [comment]
Thanks for the first version it helps me a lot.

For the second version I get some issue with the collection.

```
Running tests...
Compiling 1 file (.ex)

== Compilation error on file lib/phubme/nicknames_matcher.ex ==
** (CompileError) lib/phubme/nicknames_matcher.ex:13: undefined function |/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

With this code

``` elixir
defmodule PhubMe.NicknamesMatcher do
  def match_nicknames({full_comment, github_nicknames, sender, comment_parsed}) do
    {:ok, full_comment, matching_nicknames(github_nicknames), sender, comment_parsed }
  end

  def match_nicknames(_) do
    {:no_nicknames_found}
  end

  defp matching_nicknames([ head | tail ]) do
    case nickname_from_mix_config(head) do
      :error -> matching_nicknames(tail)
      { :ok, nickname } -> [ head | nickname | matching_nicknames(tail) ]
    end
  end

  defp matching_nicknames([]) do
    []
  end

  defp nickname_from_mix_config(github_nick_head) do
    case Application.fetch_env(:phubme, String.to_atom(List.first(github_nick_head))) do
      {:ok, slack_nickname} -> [slack_nickname]
      :error -> :error
    end
  end
end
```

**Comment by nicoolas25** [comment]
I'm a bit late but the `nickname_from_mix_config` was a list a the time. This made it incompatible with the `[ first | second | tail ]` notation. Actually this notation was not Elixir, the Elixir version would have been `[ head, nickname | matching_nicknames(tail) ]`, sorry :-/ Still the idea is the same !

**Pull request merged**
