### PR TITLE
Try to implement forward_comment

### PR DESCRIPTION
**Pull request by benoittgt**
Lot's of issues especially with args and pipe operator. I've added some comment into the code.

1 - How to forward properly arguments to `forward_comment` and don't get the error? 
2 - Is it a good thing to add more arguments at this moment ?
3 - All my methods here are public because I want to be able to test them. Is it possible to test private methods?

### CODE REVIEW

**Comment by lypborges** [comment]
Hi, 

3 - About test private methods

http://stackoverflow.com/questions/20949358/is-there-a-way-to-test-private-functions-in-modules-in-exunit-of-elixir

A agree with José Valim on his comment, you should test behaviour and not implementation

**Comment by benoittgt** [comment]
@lypborges thanks for the answer. So I have to do the test only on `process_comment`? with the different cases?

Thanks

**Comment by lypborges** [comment]
Exactly. I think you should test you public method, in this case process_comment. Don't forget to test a fail case too.

**Comment by benoittgt** [comment]
@lypborges ok thanks I did it.

**Pull request merged**
